//! Ad blocking powered by Brave's `adblock` engine (adblock-rust), the same
//! engine that powers Brave's native adblocker.
//!
//! Two layers, both driven from one EasyList download:
//!
//!   1. **Engine** — every navigation/response the webview requests is checked
//!      against the engine via `decide-policy`; matching requests are ignored
//!      before WebKit ever fetches them.
//!   2. **WebKit content blocker** — the engine converts the same rules into
//!      WebKit's native content-blocker JSON (`into_content_blocking`), which
//!      is compiled through `UserContentFilterStore`. This also blocks
//!      subresource/media loads the policy handler never sees.
//!
//! On top of that: cosmetic (element-hiding) stylesheets and a YouTube
//! scriptlet injected at document-start, as before. No fragile hand-written
//! JSON conversion — parsing, exception handling and conversion are all done
//! by the engine.

use std::cell::RefCell;
use std::os::raw::{c_uint, c_void};
use std::path::PathBuf;

use adblock::content_blocking::CbRule;
use adblock::lists::{FilterSet, ParseOptions};
use adblock::request::Request;

use crate::webkit_ffi as ffi;

const FILTER_ID: &str = "easylist";

/// Filter lists, mirroring uBlock Origin's defaults. EasyList alone fails
/// aggressive tests (canyoublockit) — the uBO lists carry the anti-adblock
/// and annoyance rules that pass them.
struct FilterList {
    name: &'static str,
    url: &'static str,
}

const FILTER_LISTS: &[FilterList] = &[
    FilterList { name: "easylist", url: "https://easylist.to/easylist/easylist.txt" },
    FilterList { name: "easyprivacy", url: "https://easylist.to/easylist/easyprivacy.txt" },
    FilterList {
        name: "ublock-filters",
        url: "https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters.txt",
    },
    // uAssets' filters/annoyances.txt is a TEMPLATE (%timestamp% + !#include
    // directives we don't expand) — downloading it yields ~0 usable rules.
    // The easylist.to mirror serves Fanboy's Annoyance list pre-expanded.
    FilterList {
        name: "fanboy-annoyance",
        url: "https://easylist.to/easylist/fanboy-annoyance.txt",
    },
];

/// Pure ad/tracker hosts the shipped lists miss — their rules often use
/// options the content-blocker converter must skip ($redirect, $removeparam,
/// $csp) or uBO scriptlets, so the host keeps loading. Blocking the host
/// outright is safe for these.
const BUILTIN_BLOCKLIST: &[&str] = &[
    "||ads.youtube.com^",
    "||ads-api.tiktok.com^",
    "||ads-sg.tiktok.com^",
    "||ads.tiktok.com^",
    "||business-api.tiktok.com^",
    "||log.byteoversea.com^",
    "||analyticsengine.s3.amazonaws.com^",
    "||analytics.s3.amazonaws.com^",
    "||m.doubleclick.net^",
    "||mediavisor.doubleclick.net^",
    "||afs.googlesyndication.com^",
    "||udcm.yahoo.com^",
    "||analytics.query.yahoo.com^",
    "||partnerads.ysm.yahoo.com^",
    "||log.fc.yahoo.com^",
    "||appmetrica.yandex.ru^",
    "||ads-api.twitter.com^",
    "||ads.pinterest.com^",
    "||an.facebook.com^",
];

/// YouTube's own player/telemetry endpoints. Some list rules match paths
/// under these (stats pings, innertube calls); when one gets blocked the
/// player intermittently fails with "Something went wrong". uBlock never
/// lets those rules fire here — explicit exceptions keep playback stable.
/// Exception (@@) rules convert to `ignore-previous-rules` and are ordered
/// last in the content-blocker export, so they win over any block above.
const BUILTIN_ALLOWLIST: &[&str] = &[
    "@@||youtube.com/api/",
    "@@||youtube.com/youtubei/",
    "@@||youtube.com/get_video_info*",
    "@@||googlevideo.com/videoplayback*",
];

/// Shared app-data dir (also used by session persistence).
pub fn data_dir_shared() -> PathBuf {
    data_dir()
}

fn data_dir() -> PathBuf {
    std::env::var_os("HOME")
        .map(std::path::PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("/tmp"))
        .join(".local/share/light-browser")
}

/// Per-list raw cache (kept to avoid re-downloading when only the JSON
/// generation changes).
fn list_cache_path(name: &str) -> PathBuf {
    data_dir().join("lists").join(format!("{name}.txt"))
}

/// Content-blocker rules generated by the engine. Bump `v` when built-in
/// rules or the on-disk format change to force regeneration (stale files
/// persist on disk). v9: pretty JSON so chunking can slice real arrays.
fn rules_cache_path() -> PathBuf {
    data_dir().join("easylist.engine.v9.json")
}

fn filter_store_dir() -> PathBuf {
    data_dir().join("filters")
}

/// Reject template/stub responses: uAssets master files like
/// filters/annoyances.txt use `%timestamp%` placeholders and `!#include`
/// directives that we don't expand — caching one silently yields 0 rules.
fn list_text_looks_valid(text: &str) -> bool {
    !text.trim().is_empty()
        && !text.contains("%timestamp%")
        && !text.lines().any(|l| l.starts_with("!#include"))
}

// ── Rule generation (engine-driven) ──────────────────────────────────────────

/// Append built-in block/allow rules to the combined list text. The
/// allowlist MUST come after everything else — exceptions win in the
/// content-blocker ordering (`ignore-previous-rules` last).
fn augment_lists(text: &str) -> String {
    let mut out = String::with_capacity(text.len() + 2048);
    out.push_str(text);
    out.push_str("! --- light-browser built-in rules ---\n");
    for r in BUILTIN_BLOCKLIST {
        out.push_str(r);
        out.push('\n');
    }
    for r in BUILTIN_ALLOWLIST {
        out.push_str(r);
        out.push('\n');
    }
    out
}

/// Parse the combined lists with the engine and convert to WebKit
/// content-blocker JSON. Returns `None` when no rule could be converted.
pub fn build_rules(easylist: &str) -> Option<String> {
    let mut set = FilterSet::new(true); // debug: keep raw lines for conversion
    set.add_filter_list(easylist.to_string(), ParseOptions::default());
    let (rules, _used) = set.into_content_blocking().ok()?;
    if rules.is_empty() {
        return None;
    }
    // Pretty JSON: the compiler slices this file into chunks, and per-chunk
    // parsing needs real array boundaries.
    serde_json::to_string_pretty(&rules).ok()
}

// ── Rule chunking (WebKit per-save limit) ────────────────────────────────

/// WebKit's UserContentFilterStore rejects a single save with too many
/// rules ("Too many rules in JSON array" — hit at ~180k, passed at 132k).
/// Compile in slices well under the cap. Filters apply in add order and
/// later filters win, so exceptions (`ignore-previous-rules`) must land in
/// the LAST chunk — the engine's export already orders them last, so
/// preserving order across the slice boundary keeps that guarantee.
const MAX_RULES_PER_CHUNK: usize = 100_000;

fn chunk_rules_json(json: &str) -> Vec<String> {
    let rules: Vec<CbRule> = match serde_json::from_str(json) {
        Ok(r) => r,
        Err(e) => {
            eprintln!("[adblock] cannot re-parse rules for chunking: {e}");
            return vec![json.to_string()];
        }
    };
    if rules.len() <= MAX_RULES_PER_CHUNK {
        return vec![json.to_string()];
    }
    rules
        .chunks(MAX_RULES_PER_CHUNK)
        .map(|chunk| serde_json::to_string(chunk).unwrap_or_default())
        .filter(|s| !s.is_empty())
        .collect()
}

// ── Shared state (main thread only) ──────────────────────────────────────────

enum State {
    Idle,
    Loading(Vec<*mut c_void>), // pending user content managers
    Ready(FilterBundle),
    Failed,
}

/// Compiled network filters (one per rule chunk) + cosmetic style sheets +
/// scriptlets (app lifetime).
struct FilterBundle {
    /// One compiled content filter per rule chunk — WebKit caps a single
    /// store save, so big lists are split. Filters apply in add order and
    /// later ones win, which preserves the exceptions-last ordering.
    filters: Vec<*mut c_void>,
    style_sheets: Vec<*mut c_void>,
    user_scripts: Vec<*mut c_void>,
}

thread_local! {
    static SHARED: RefCell<State> = const { RefCell::new(State::Idle) };
}

/// Attach the adblock filters to a webview's user content manager. Call once
/// per webview right after creation. If the filter isn't ready yet, the
/// manager is queued and filters are attached when loading finishes.
pub fn attach_to_webview(wv_ptr: *mut ffi::WebKitWebView) {
    unsafe {
        ffi::g_signal_connect_data(
            wv_ptr as *mut ffi::GObject,
            c"decide-policy".as_ptr(),
            Some(std::mem::transmute(
                policy_decide_trampoline as unsafe extern "C" fn(
                    *mut ffi::WebKitWebView,
                    *mut c_void, // WebKitPolicyDecision
                    c_uint,      // decision type (POLICY_DECISION_TYPE_*)
                    *mut c_void,
                ),
            )),
            std::ptr::null_mut(),
            None,
            0,
        );
    }

    // Auto-deny notification permission requests — sites push ads through
    // them and the prompts themselves are an annoyance vector.
    unsafe {
        ffi::g_signal_connect_data(
            wv_ptr as *mut ffi::GObject,
            c"permission-request".as_ptr(),
            Some(std::mem::transmute(
                permission_deny_trampoline
                    as unsafe extern "C" fn(
                        *mut ffi::WebKitWebView,
                        *mut c_void,
                        *mut c_void,
                    ) -> i32,
            )),
            std::ptr::null_mut(),
            None,
            0,
        );
    }

    let manager = unsafe { ffi::webkit_web_view_get_user_content_manager(wv_ptr) };
    if manager.is_null() {
        return;
    }

    SHARED.with(|shared| {
        let mut state = shared.borrow_mut();
        match &mut *state {
            State::Ready(bundle) => unsafe {
                apply_bundle(bundle, manager);
            },
            State::Loading(pending) => pending.push(manager),
            State::Idle | State::Failed => {
                *state = State::Loading(vec![manager]);
                drop(state);
                start_download();
            }
        }
    });
}

/// Auto-deny every permission request (notifications, geolocation, etc.).
/// TRUE stops WebKit's default handler (which would show a dialog).
unsafe extern "C" fn permission_deny_trampoline(
    _web_view: *mut ffi::WebKitWebView,
    request: *mut c_void,
    _data: *mut c_void,
) -> i32 {
    unsafe extern "C" {
        fn webkit_permission_request_deny(request: *mut c_void);
    }
    if !request.is_null() {
        webkit_permission_request_deny(request);
    }
    1
}

/// Engine check on every navigation/response. `decide-policy` fires on the
/// main thread with the decision type as its third argument; unhandled
/// decisions are left for WebKit's default behavior.
unsafe extern "C" fn policy_decide_trampoline(
    web_view: *mut ffi::WebKitWebView,
    decision: *mut c_void,
    decision_type: c_uint,
    _data: *mut c_void,
) {
    handle_policy_decision(web_view, decision, decision_type);
}

unsafe fn handle_policy_decision(
    web_view: *mut ffi::WebKitWebView,
    decision: *mut c_void,
    decision_type: c_uint,
) {
    // Downloads first: a response whose MIME type the view can't render
    // (zip, pdf attachment, ...) must be answered with `download` or WebKit
    // never starts one — download-started only fires after this decision.
    // Checked before the engine so list rules can never swallow a download.
    if decision_type == ffi::POLICY_DECISION_TYPE_RESPONSE
        && ffi::webkit_response_policy_decision_is_mime_type_supported(decision) == 0
    {
        if let Some(dl_uri) = decision_uri(decision, decision_type) {
            eprintln!("[download] policy: {dl_uri}");
        }
        ffi::webkit_policy_decision_download(decision);
        return;
    }

    let uri = decision_uri(decision, decision_type);
    let Some(uri) = uri else { return };

    let source = main_frame_uri(web_view).unwrap_or_default();

    // Popups: only NEW_WINDOW_ACTION decisions open a new window. Blocking
    // script-initiated ones (no user gesture) kills ad popups and popunders
    // while clicks on links/OAuth buttons pass. Same-frame navigation types
    // (NAVIGATION_ACTION) are never touched — that's how a window.location
    // assignment from our own new-tab page gets misread as a popup.
    if decision_type == ffi::POLICY_DECISION_TYPE_NEW_WINDOW_ACTION {
        let action = ffi::webkit_navigation_policy_decision_get_navigation_action(decision);
        if !action.is_null()
            && unsafe { ffi::webkit_navigation_action_is_user_gesture(action) } == 0
        {
            ffi::webkit_policy_decision_ignore(decision);
            eprintln!("[adblock] blocked popup: {uri}");
            return;
        }
    }

    let is_response = decision_type == ffi::POLICY_DECISION_TYPE_RESPONSE;
    let request_type = if is_response { "subdocument" } else { "document" };

    let blocked = SHARED.with(|shared| {
        let state = shared.borrow();
        let State::Ready(_) = &*state else {
            return false;
        };
        let Some(engine) = engine() else { return false };
        let Ok(req) = Request::new(&uri, &source, request_type, "GET") else {
            return false;
        };
        // BlockerResult in 0.13: `filter` = matched rule, `exception` =
        // matched allow-rule. Blocked only when a rule matched and no
        // exception overrode it.
        let m = engine.check_network_request(&req);
        m.exception.is_none() && m.filter.is_some()
    });

    if blocked {
        ffi::webkit_policy_decision_ignore(decision);
        eprintln!("[adblock] blocked request: {uri}");
    }
}

/// The compiled engine lives in a global: built once on a background thread,
/// then only ever read from the main thread. `OnceLock` gives us safe
/// cross-thread publication; reads take a short lock-free hit only until the
/// engine is swapped in.
static ENGINE: std::sync::OnceLock<adblock::Engine> = std::sync::OnceLock::new();

fn engine() -> Option<&'static adblock::Engine> {
    ENGINE.get()
}

unsafe fn decision_uri(decision: *mut c_void, decision_type: c_uint) -> Option<String> {
    let request = if decision_type == ffi::POLICY_DECISION_TYPE_RESPONSE {
        ffi::webkit_response_policy_decision_get_request(decision)
    } else {
        let action = ffi::webkit_navigation_policy_decision_get_navigation_action(decision);
        if action.is_null() {
            return None;
        }
        ffi::webkit_navigation_action_get_request(action)
    };
    if request.is_null() {
        return None;
    }
    let uri = ffi::webkit_uri_request_get_uri(request);
    if uri.is_null() {
        None
    } else {
        Some(
            std::ffi::CStr::from_ptr(uri)
                .to_string_lossy()
                .into_owned(),
        )
    }
}

unsafe fn main_frame_uri(web_view: *mut ffi::WebKitWebView) -> Option<String> {
    let resource = ffi::webkit_web_view_get_main_resource(web_view);
    if resource.is_null() {
        return None;
    }
    unsafe extern "C" {
        fn webkit_web_resource_get_uri(resource: *mut c_void) -> *const std::os::raw::c_char;
    }
    let uri = webkit_web_resource_get_uri(resource);
    if uri.is_null() {
        None
    } else {
        Some(
            std::ffi::CStr::from_ptr(uri)
                .to_string_lossy()
                .into_owned(),
        )
    }
}

unsafe fn apply_bundle(bundle: &FilterBundle, manager: *mut c_void) {
    for filter in &bundle.filters {
        if !filter.is_null() {
            ffi::webkit_user_content_manager_add_filter(manager, *filter);
        }
    }
    for sheet in &bundle.style_sheets {
        ffi::webkit_user_content_manager_add_style_sheet(manager, *sheet);
    }
    for script in &bundle.user_scripts {
        ffi::webkit_user_content_manager_add_script(manager, *script);
    }
}

fn start_download() {
    std::thread::spawn(|| {
        let lists = ensure_lists();
        gtk4::glib::MainContext::default().invoke(move || {
            load_into_store(lists);
        });
    });
}

/// Download (or reuse cached) all filter lists, concatenated. Blocking
/// network I/O — background thread only. A list that fails to download is
/// skipped with a warning as long as at least one list is available.
fn ensure_lists() -> Result<String, String> {
    let mut combined = String::new();
    let mut loaded = 0usize;
    let mut last_err = String::new();

    for list in FILTER_LISTS {
        let cache = list_cache_path(list.name);
        let text = match std::fs::read_to_string(&cache) {
            Ok(t) if list_text_looks_valid(&t) => t,
            _ => match download_list(list.url) {
                Ok(t) => {
                    if let Some(parent) = cache.parent() {
                        let _ = std::fs::create_dir_all(parent);
                    }
                    if let Err(e) = std::fs::write(&cache, t.as_bytes()) {
                        eprintln!("[adblock] cannot cache {}: {e}", list.name);
                    }
                    t
                }
                Err(e) => {
                    eprintln!("[adblock] list {} unavailable: {e}", list.name);
                    last_err = e;
                    continue;
                }
            },
        };
        let rules = text.lines().count();
        eprintln!("[adblock] list ready: {} ({rules} lines)", list.name);
        combined.push_str(&text);
        combined.push('\n');
        loaded += 1;
    }

    if loaded == 0 {
        return Err(last_err);
    }
    Ok(combined)
}

fn download_list(url: &str) -> Result<String, String> {
    for (cmd, args) in [
        ("curl", vec!["-fsSL", "--max-time", "60", url]),
        ("wget", vec!["-qO-", "-T", "60", url]),
    ] {
        if let Ok(out) = std::process::Command::new(cmd).args(&args).output() {
            if out.status.success() && !out.stdout.is_empty() {
                let text = String::from_utf8_lossy(&out.stdout).into_owned();
                if list_text_looks_valid(&text) {
                    return Ok(text);
                }
            }
        }
    }
    Err(format!("could not download {url} (curl/wget missing, offline, or source served a template/stub)"))
}

/// GAsyncReadyCallback: the source object IS the filter store. Drives the
/// chunk pipeline: collect this chunk's filter, save the next chunk, or hand
/// the full bundle over when all chunks are done.
unsafe extern "C" fn load_trampoline(
    store: *mut ffi::GObject,
    result: *mut c_void,
    data: *mut c_void,
) {
    let mut err: *mut ffi::GError = std::ptr::null_mut();
    let filter = ffi::webkit_user_content_filter_store_save_from_file_finish(
        store as *mut c_void,
        result,
        &mut err,
    );

    let ctx = &mut *(data as *mut CompileCtx);

    if filter.is_null() {
        let msg = if err.is_null() {
            "unknown error".to_string()
        } else {
            std::ffi::CStr::from_ptr((*err).message).to_string_lossy().into_owned()
        };
        eprintln!("[adblock] filter compile failed: {msg}");
        // A chunk that fails leaves the rule set incomplete — partial filters
        // would break the exceptions-last ordering, so compile nothing.
        cleanup_compile(data);
        SHARED.with(|s| *s.borrow_mut() = State::Failed);
        return;
    }

    ctx.filters.push(filter);
    ctx.index += 1;
    if ctx.index < ctx.chunks.len() {
        start_chunk_save(data);
        return;
    }

    // All chunks compiled — take ownership and hand over the bundle.
    let mut ctx = Box::from_raw(data as *mut CompileCtx);
    let filter_count = ctx.filters.len();
    let bundle = FilterBundle {
        filters: std::mem::take(&mut ctx.filters),
        style_sheets: STAGED_SHEETS.with(|s| std::mem::take(&mut *s.borrow_mut())),
        user_scripts: STAGED_SCRIPTS.with(|s| std::mem::take(&mut *s.borrow_mut())),
    };

    SHARED.with(|shared| {
        let mut state = shared.borrow_mut();
        match std::mem::replace(&mut *state, State::Failed) {
            State::Loading(pending) => {
                for manager in &pending {
                    apply_bundle(&bundle, *manager);
                }
            }
            other => {
                *state = other;
            }
        }
        *state = State::Ready(bundle);
    });
    eprintln!(
        "[adblock] EasyList compiled & active ({filter_count} filter(s) + engine + cosmetic + scriptlets)",
    );
}

fn load_into_store(lists: Result<String, String>) {
    let easylist = match lists {
        Ok(t) => t,
        Err(e) => {
            eprintln!("[adblock] disabled: {e}");
            SHARED.with(|s| *s.borrow_mut() = State::Failed);
            return;
        }
    };

    // 1. Build the live engine for decide-policy checks (once per process).
    let all_rules = augment_lists(&easylist);
    if ENGINE.get().is_none() {
        let mut set = FilterSet::new(false);
        set.add_filter_list(all_rules.clone(), ParseOptions::default());
        let engine = adblock::Engine::new_with_filter_set(set);
        let _ = ENGINE.set(engine);
        eprintln!("[adblock] engine ready (decide-policy layer active)");
    }

    // 2. Engine conversion → WebKit content-blocker JSON (cached on disk).
    let rules_source = all_rules;
    let rules_json = match std::fs::read_to_string(rules_cache_path()) {
        Ok(json) if !json.trim().is_empty() => Some(json),
        _ => {
            let json = build_rules(&rules_source);
            if let Some(json) = &json {
                let path = rules_cache_path();
                if let Some(parent) = path.parent() {
                    let _ = std::fs::create_dir_all(parent);
                }
                let _ = std::fs::write(&path, json.as_bytes());
            }
            json
        }
    };

    // 2. Build cosmetic style sheets + scriptlets (independent of compile).
    unsafe { build_style_sheets(&easylist) };
    let scripts = unsafe { build_scriptlets() };
    STAGED_SCRIPTS.with(|s| *s.borrow_mut() = scripts);

    // 3. Compile the JSON into the store (async) and hand the filter over.
    let Some(json) = rules_json else {
        eprintln!("[adblock] engine produced no convertible rules");
        SHARED.with(|s| {
            let mut st = s.borrow_mut();
            let sheets = STAGED_SHEETS.with(|s| std::mem::take(&mut *s.borrow_mut()));
            if !sheets.is_empty() {
                *st = State::Ready(FilterBundle {
                    filters: Vec::new(),
                    style_sheets: sheets,
                    user_scripts: STAGED_SCRIPTS.with(|s| std::mem::take(&mut *s.borrow_mut())),
                });
            } else {
                *st = State::Failed;
            }
        });
        return;
    };

    // 3. Compile the JSON into the store (async), one chunk per save —
    // WebKit rejects a single save over its per-file rule cap.
    let chunks = chunk_rules_json(&json);
    if chunks.is_empty() {
        eprintln!("[adblock] chunking produced no rule files");
        SHARED.with(|s| *s.borrow_mut() = State::Failed);
        return;
    }
    eprintln!(
        "[adblock] compiling {} rule chunk(s) from {}",
        chunks.len(),
        rules_cache_path().display()
    );

    let store_dir = filter_store_dir();
    let _ = std::fs::create_dir_all(&store_dir);

    let c_dir =
        std::ffi::CString::new(store_dir.to_string_lossy().as_ref()).unwrap();
    let store = unsafe { ffi::webkit_user_content_filter_store_new(c_dir.as_ptr()) };
    // `store` is intentionally leaked — lives for the app lifetime.

    let ctx = Box::new(CompileCtx { store, chunks, index: 0, filters: Vec::new() });
    let data = Box::into_raw(ctx) as *mut c_void;

    // Kick off the first save; load_trampoline drives the rest.
    unsafe { start_chunk_save(data) };
}

/// State for the multi-chunk compile: chunks left to save + filters already
/// compiled, in order. Freed in load_trampoline when compilation ends.
struct CompileCtx {
    store: *mut c_void,
    chunks: Vec<String>,
    index: usize,
    filters: Vec<*mut c_void>,
}

/// Save chunk `ctx.index` to the store under a unique id.
unsafe fn start_chunk_save(data: *mut c_void) {
    let ctx = &mut *(data as *mut CompileCtx);
    let json = &ctx.chunks[ctx.index];
    let tmp = rules_cache_path()
        .with_extension(format!("chunk{}-compile.json", ctx.index));
    if std::fs::write(&tmp, json.as_bytes()).is_err() {
        eprintln!("[adblock] cannot write rules chunk {} for compilation", ctx.index);
        cleanup_compile(data);
        SHARED.with(|s| *s.borrow_mut() = State::Failed);
        return;
    }

    let c_path = std::ffi::CString::new(tmp.to_string_lossy().as_ref()).unwrap();
    let file = ffi::g_file_new_for_path(c_path.as_ptr());
    let c_id =
        std::ffi::CString::new(format!("{}-c{}", FILTER_ID, ctx.index)).unwrap();

    ffi::webkit_user_content_filter_store_save_from_file(
        ctx.store,
        c_id.as_ptr(),
        file,
        std::ptr::null_mut(),
        Some(load_trampoline),
        data,
    );
}

/// Free the compile state (and any compiled filters not yet handed over).
unsafe fn cleanup_compile(data: *mut c_void) {
    if data.is_null() {
        return;
    }
    let ctx = Box::from_raw(data as *mut CompileCtx);
    for f in ctx.filters {
        ffi::webkit_user_content_filter_unref(f);
    }
}

unsafe fn build_style_sheets(easylist: &str) {
    // Global element-hiding selectors, straight from the list (## rules
    // without a domain prefix). The engine's content-blocker export already
    // carries domain-qualified cosmetic rules, so only the global ones are
    // duplicated here.
    let mut global_selectors: Vec<String> = Vec::new();
    for line in easylist.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('!') || line.starts_with('[') {
            continue;
        }
        if line.contains("#@#") {
            continue; // exception hiding — do not hide
        }
        if let Some((lhs, rhs)) = line.split_once("##") {
            if lhs.trim().is_empty() {
                let selector = rhs.trim();
                if !selector.is_empty() && global_selectors.len() < 3000 {
                    global_selectors.push(selector.to_string());
                }
            }
        }
    }

    let mut sheets: Vec<*mut c_void> = Vec::new();
    if !global_selectors.is_empty() {
        let joined = global_selectors.join(",\n");
        let css = format!(
            "{joined} {{ display: none !important; visibility: hidden !important; }}\n"
        );
        if let Some(s) = make_style_sheet(&css, &[]) {
            sheets.push(s);
        }
    }

    STAGED_SHEETS.with(|s| *s.borrow_mut() = sheets);
}

unsafe fn make_style_sheet(
    css: &str,
    allow_list: &[*const std::os::raw::c_char],
) -> Option<*mut c_void> {
    let c_css = std::ffi::CString::new(css).ok()?;
    let allow_ptr = if allow_list.is_empty() {
        std::ptr::null()
    } else {
        allow_list.as_ptr()
    };
    let sheet = ffi::webkit_user_style_sheet_new(
        c_css.as_ptr(),
        0, // WEBKIT_USER_CONTENT_INJECT_ALL_FRAMES
        0, // WEBKIT_USER_STYLE_LEVEL_USER
        allow_ptr,
        std::ptr::null(),
    );
    if sheet.is_null() {
        None
    } else {
        Some(sheet)
    }
}

/// JS scriptlets — uBlock-style injected scripts for players that serve ads
/// from the video CDN itself (YouTube), where network rules are useless.
///
/// The key technique is uBO's `json-prune adPlacements adSlots`: hook
/// `JSON.parse` at document-start and strip ad scheduling out of every
/// payload BEFORE the player sees it. The old approach deleted those fields
/// after the ad module had already read them — too late.
fn yt_user_script_source() -> &'static str {
    r#"
(function () {
    if (window.__lbAdKill) return; window.__lbAdKill = true;

    // ---- 1. json-prune: strip ad data from every JSON payload the page
    // parses. The player never learns an ad was scheduled. (Same technique
    // as uBO's json-prune — parsed data only, player API untouched.)
    var PRUNE_KEYS = ['adPlacements', 'adSlots', 'auxiliaryUi'];
    var nativeParse = JSON.parse;
    JSON.parse = function () {
        var obj = nativeParse.apply(this, arguments);
        try { prune(obj, 0); } catch (e) {}
        return obj;
    };
    function prune(obj, depth) {
        if (!obj || typeof obj !== 'object' || depth > 8) return;
        for (var k in obj) {
            if (PRUNE_KEYS.indexOf(k) !== -1) { delete obj[k]; continue; }
            var v = obj[k];
            if (v && typeof v === 'object') prune(v, depth + 1);
        }
    }

    // ---- 2. Hide ad UI (CSS only — never remove player-owned nodes; the
    // player keeps references into its own DOM and breaks when they vanish).
    var AD_UI = [
        '.ytp-ad-module', '.ytp-ad-player-overlay', '.ytp-ad-text',
        '.ytp-ad-image', '.ytp-ad-video', '.ytp-ad-preview-container',
        '.ytp-ad-action-interstitial', '.ytp-ad-message-container',
        'ytd-promoted-sparkles-web-renderer', 'ytd-promoted-video-renderer',
        'ytd-compact-promoted-video-renderer', 'ytd-ad-slot-renderer',
        '#player-ads', 'ytd-in-feed-ad-layout-renderer',
        'ytd-banner-promo-renderer', 'ytd-statement-banner-renderer',
        'tp-yt-paper-dialog.ytd-popup-container ytd-mealbar-promo-renderer'
    ].join(',');
    var css = document.createElement('style');
    css.textContent = AD_UI + ' { display: none !important; }';
    (document.head || document.documentElement).appendChild(css);

    // ---- 3. Auto-click "Skip" if YouTube still shows one. Never drive the
    // player API from here — yanking playback mid-stream is what makes it
    // die with "Something went wrong".
    function tick() {
        var skip = document.querySelector(
            '.ytp-ad-skip-button, .ytp-ad-skip-button-modern, .ytp-skip-ad-button');
        if (skip) { try { skip.click(); } catch (e) {} }
    }
    setInterval(tick, 500);
    new MutationObserver(tick).observe(document.documentElement,
        { childList: true, subtree: true });
})();
"#
}

unsafe fn build_scriptlets() -> Vec<*mut c_void> {
    let mut scripts = Vec::new();
    let allow = [c"*://www.youtube.com/*", c"*://m.youtube.com/*", c"*://youtube.com/*"];
    let allow_ptrs: Vec<*const std::os::raw::c_char> =
        allow.iter().map(|s| s.as_ptr()).chain(std::iter::once(std::ptr::null())).collect();

    let c_js = std::ffi::CString::new(yt_user_script_source()).unwrap();
    // 0 = ALL_FRAMES; injection_time 0 = document-start.
    let script = ffi::webkit_user_script_new(
        c_js.as_ptr(),
        0,
        0,
        allow_ptrs.as_ptr(),
        std::ptr::null(),
    );
    if !script.is_null() {
        scripts.push(script);
    }
    scripts
}

thread_local! {
    static STAGED_SHEETS: RefCell<Vec<*mut c_void>> = const { RefCell::new(Vec::new()) };
    static STAGED_SCRIPTS: RefCell<Vec<*mut c_void>> = const { RefCell::new(Vec::new()) };
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE: &str = "\
! EasyList sample
||doubleclick.net^
/ads/banner.js
@@||good.example.com^$document
bannersite.com##.ad
##.tracker, .pixel
#@#.keepme
example.com/ads/*banner
||googlesyndication.com^$third-party,script
||ads.example.com^$domain=foo.com|bar.com
google.*##.ad-slot
example.com##+js(abort-on-property-read, x)
example.com##.ad:has(.inner)
";

    #[test]
    fn converted_rules_are_valid_json() {
        let json = build_rules(SAMPLE).expect("rules should convert");
        let parsed: Vec<CbRule> = serde_json::from_str(&json).expect("valid WebKit JSON");
        assert!(!parsed.is_empty());
    }

    #[test]
    fn blocks_known_ad_and_allows_exceptions() {
        let json = build_rules(SAMPLE).expect("rules should convert");
        let rules: Vec<CbRule> = serde_json::from_str(&json).unwrap();
        assert!(
            rules
                .iter()
                .any(|r| r.action.selector.as_deref().unwrap_or("").contains(".tracker")),
            "global cosmetic selector should be exported"
        );

        // Engine path: same rules via the engine, so decide-policy blocking
        // is what the runtime uses.
        let mut set = FilterSet::new(true);
        set.add_filter_list(SAMPLE.to_string(), ParseOptions::default());
        let engine = adblock::Engine::new_with_filter_set(set);

        let blocked = |url: &str, source: &str, ty: &str| {
            let req = Request::new(url, source, ty, "GET").unwrap();
            let m = engine.check_network_request(&req);
            m.exception.is_none() && m.filter.is_some()
        };

        assert!(blocked(
            "https://ad.doubleclick.net/ddm/adj/x",
            "https://news.example.com/",
            "script"
        ));
        // Third-party script rule from the sample list.
        assert!(blocked(
            "https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js",
            "https://news.example.com/",
            "script"
        ));
        // `$domain=` restriction: blocks on the listed domains only.
        assert!(blocked("https://ads.example.com/x.js", "https://foo.com/", "script"));
        assert!(!blocked("https://ads.example.com/x.js", "https://other.com/", "script"));
        // The engine never blocks main-document loads, and the `@@` exception
        // must surface as an allow rather than a block.
        assert!(!blocked(
            "https://good.example.com/page",
            "https://good.example.com/page",
            "document"
        ));
        assert!(blocked(
            "https://cdn.example.com/ads/banner.js",
            "https://news.example.com/",
            "script"
        ));
        assert!(blocked(
            "https://example.com/ads/superbanner.js",
            "https://example.com/",
            "script"
        ));
    }

    #[test]
    fn augment_puts_exceptions_last() {
        let out = augment_lists("||ads.example.com^\n");
        let block_pos = out.find("||ads.example.com^").unwrap();
        let allow_pos = out.find("@@||youtube.com/api/").unwrap();
        assert!(block_pos < allow_pos, "exceptions must come after blocks");
    }

    #[test]
    fn chunking_splits_big_rulesets_and_keeps_exceptions_last() {
        let rules: Vec<CbRule> = (0..(MAX_RULES_PER_CHUNK + 500))
            .map(|i| {
                let json = format!(
                    r#"{{"trigger":{{"url-filter":"host{i}.example"}},"action":{{"type":"block"}}}}"#
                );
                serde_json::from_str(&json).unwrap()
            })
            .collect();
        let json = serde_json::to_string_pretty(&rules).unwrap();

        let chunks = chunk_rules_json(&json);
        assert_eq!(chunks.len(), 2, "oversized ruleset must split into 2 saves");
        for chunk in &chunks {
            let parsed: Vec<CbRule> =
                serde_json::from_str(chunk).expect("chunk is valid WebKit JSON");
            assert!(parsed.len() <= MAX_RULES_PER_CHUNK);
        }
        // Order is preserved across the boundary (exceptions-last guarantee).
        let first: Vec<CbRule> = serde_json::from_str(&chunks[0]).unwrap();
        let last: Vec<CbRule> = serde_json::from_str(&chunks[1]).unwrap();
        assert_eq!(first[0].trigger.url_filter, "host0.example");
        assert_eq!(last.last().unwrap().trigger.url_filter, "host100499.example");

        // Small rulesets stay as a single unmodified file.
        let small = chunk_rules_json(r#"[]"#);
        assert_eq!(small.len(), 1);
    }

    #[test]
    fn yt_scriptlet_targets_player_ads() {
        let js = yt_user_script_source();
        assert!(js.contains("adPlacements"));
        // json-prune must hook at document-start, before the player parses.
        assert!(js.contains("JSON.parse"));
        // The watchdog that force-stops the player is gone: calling
        // stopVideo()/seekTo() mid-playback kills the player with
        // "Something went wrong".
        assert!(!js.contains("stopVideo"));
        assert!(!js.contains("seekTo"));
        // Ad UI is hidden with CSS, never removed from the player's DOM.
        assert!(js.contains("display: none"));
        assert!(!js.contains("el.remove()"));
    }
}
